"""vessel-fuel-model public API."""

from .current import (
    current_induced_resistance,
    current_vector_component,
    fuel_savings_from_current,
    speed_over_ground,
    transit_time_hours,
)
from .engine import auxiliary_fuel, boiler_fuel, sfoc_curve
from .environment import sw_density, sw_viscosity
from .fouling import fouling_delta_cf
from .model import calibrate_model, calibration_report, fuel_components, fuel_model, validate_model
from .resistance import (
    blendermann_wind_resistance,
    holtrop_mennen_resistance,
    kwon_resistance,
    stawave1_resistance,
)
from .research import (
    HybridResidualModel,
    PhysicsOnlyModel,
    PureMLModel,
    SpeedPowerBaseline,
    align_and_merge_temporal_data,
    build_feature_matrix,
    clean_observations,
    conformal_interval,
    download_copernicus_era5,
    download_gebco_bathymetry,
    download_noaa_ais_archive,
    generate_synthetic_operational_dataset,
    fuse_operational_data,
    load_ais_segments,
    load_engine_noon,
    load_metocean,
    load_vessel_particulars,
    permutation_sensitivity,
    run_benchmark_suite,
    split_train_val_test,
    validate_data_schema,
)

__all__ = [
    "auxiliary_fuel",
    "boiler_fuel",
    "sfoc_curve",
    "sw_density",
    "sw_viscosity",
    "fouling_delta_cf",
    "fuel_model",
    "fuel_components",
    "calibrate_model",
    "calibration_report",
    "validate_model",
    "holtrop_mennen_resistance",
    "blendermann_wind_resistance",
    "stawave1_resistance",
    "kwon_resistance",
    "current_vector_component",
    "speed_over_ground",
    "transit_time_hours",
    "current_induced_resistance",
    "fuel_savings_from_current",
    "run_benchmark_suite",
    "build_feature_matrix",
    "clean_observations",
    "generate_synthetic_operational_dataset",
    "load_ais_segments",
    "load_metocean",
    "load_vessel_particulars",
    "load_engine_noon",
    "fuse_operational_data",
    "download_noaa_ais_archive",
    "download_copernicus_era5",
    "download_gebco_bathymetry",
    "align_and_merge_temporal_data",
    "validate_data_schema",
    "split_train_val_test",
    "HybridResidualModel",
    "PhysicsOnlyModel",
    "PureMLModel",
    "SpeedPowerBaseline",
    "conformal_interval",
    "permutation_sensitivity",
]
